export const DANG_NHAP_ACTION = "DANG_NHAP_ACTION";
export const SET_THONG_TIN_NGUOI_DUNG = "SET_THONG_TIN_NGUOI_DUNG";

export const SET_DANH_SACH_NGUOI_DUNG = "SET_DANH_SACH_NGUOI_DUNG";
export const SET_DANH_SACH_MA_LOAI_NGUOI_DUNG =
  "SET_DANH_SACH_MA_LOAI_NGUOI_DUNG";
